FROM bitnami/spark:3.5.1

USER root

# Instala o Python3 e psycopg2
RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install psycopg2-binary && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia os JARs necessários para o diretório de JARs do Spark
COPY libs/spark-sql-kafka-0-10_2.12-3.5.1.jar /opt/bitnami/spark/jars/
COPY libs/postgresql-42.2.19.jar /opt/bitnami/spark/jars/
COPY libs/kafka-clients-3.5.1.jar /opt/bitnami/spark/jars/  

USER 1001
